-- Generated from MySQL export for Supabase PostgreSQL
-- Review and run in Supabase SQL Editor or migrations

CREATE TABLE IF NOT EXISTS "account_company" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text,
  "company_name" text,
  "company_email" text,
  "company_phone" text,
  "company_address" text,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "account_companystaff" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" text,
  "password" text,
  "is_company_admin" integer NOT NULL,
  "is_manager" integer NOT NULL,
  "is_employee" integer NOT NULL,
  "is_active" integer NOT NULL,
  "is_authenticated" integer NOT NULL,
  "new_notification" integer NOT NULL,
  "company_id" integer,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "account_user" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "password" text NOT NULL,
  "email" text NOT NULL,
  "full_name" text,
  "is_admin" integer NOT NULL,
  "is_employee" integer NOT NULL,
  "is_staff" integer NOT NULL,
  "is_superuser" integer NOT NULL,
  "is_active" integer NOT NULL,
  "last_login" timestamptz,
  "date_joined" timestamptz NOT NULL,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "account_user_groups" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "group_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "account_user_user_permissions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_asign" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "description" text,
  "created_date" date NOT NULL,
  "assigned_to_id" integer,
  "employee_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_client" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "client_first_name" text NOT NULL,
  "client_last_name" text NOT NULL,
  "client_username" text NOT NULL,
  "client_email" text NOT NULL,
  "client_id" text NOT NULL,
  "client_address" text NOT NULL,
  "technology" text,
  "description" text,
  "client_phone" text NOT NULL,
  "client_status" text NOT NULL,
  "company_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_emailnotification" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "message_id" text NOT NULL,
  "sender_email" text NOT NULL,
  "sender_name" text NOT NULL,
  "subject" text NOT NULL,
  "body_preview" text NOT NULL,
  "received_date" timestamptz,
  "is_read" integer NOT NULL,
  "created_at" timestamptz NOT NULL,
  "company_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_holiday" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "day" text NOT NULL,
  "date" text NOT NULL,
  "occassion" text NOT NULL,
  "holidaytype" text NOT NULL,
  "status" text NOT NULL,
  "company_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_lead" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "lead_name" text NOT NULL,
  "lead_email" text NOT NULL,
  "lead_phone" text NOT NULL,
  "lead_project" text NOT NULL,
  "lead_assign_staff" text NOT NULL,
  "lead_created" text NOT NULL,
  "lead_source" text NOT NULL,
  "company_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_managernotification" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "notifications" text NOT NULL,
  "is_read" integer NOT NULL,
  "user_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_mtask" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "description" text,
  "created_date" date NOT NULL,
  "assigned_to_id" integer,
  "user_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_notification" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "notify" text NOT NULL,
  "company_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "administration_task" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "description" text,
  "created_date" date NOT NULL,
  "assigned_to_id" integer,
  "company_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "auth_group" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "auth_group_permissions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "auth_permission" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "content_type_id" integer NOT NULL,
  "codename" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "django_admin_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "action_time" timestamptz NOT NULL,
  "object_id" text,
  "object_repr" text NOT NULL,
  "action_flag" integer NOT NULL,
  "change_message" text NOT NULL,
  "content_type_id" integer,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "django_content_type" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "app_label" text NOT NULL,
  "model" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "django_migrations" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "app" text NOT NULL,
  "name" text NOT NULL,
  "applied" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "django_session" (
  "session_key" text NOT NULL,
  "session_data" text NOT NULL,
  "expire_date" timestamptz NOT NULL,
  PRIMARY KEY ("session_key")
);

CREATE TABLE IF NOT EXISTS "employee_attendance" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "check_in" timestamptz NOT NULL,
  "check_out" timestamptz,
  "updated" timestamptz,
  "created" timestamptz,
  "employee_id" integer,
  "source" text NOT NULL,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "employee_department" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "department_name" text,
  "company_id" integer,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "employee_designation" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Designation_Name" text NOT NULL,
  "Department_Name_id" integer NOT NULL,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "employee_employee" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "employee_first_name" text NOT NULL,
  "employee_last_name" text NOT NULL,
  "employee_email" text NOT NULL,
  "employee_joining_date" date NOT NULL,
  "employee_designation" text NOT NULL,
  "employee_id" text NOT NULL,
  "employee_phone" text,
  "employee_salary" text NOT NULL,
  "employee_birth_date" text,
  "employee_gender" text,
  "employee_address" text,
  "employee_pin_code" text,
  "employee_state" text,
  "employee_country" text,
  "employee_image" text NOT NULL,
  "employee_created_date" timestamptz NOT NULL,
  "employee_status" text NOT NULL,
  "employee_tel" text,
  "employee_nationality" text,
  "employee_marital_status" text,
  "employee_father" text,
  "employee_mother" text,
  "employee_emergency_primary_name" text,
  "employee_emergency_primary_relationship" text,
  "employee_emergency_primary_phone1" text,
  "employee_emergency_primary_phone2" text,
  "employee_education_institution" text,
  "employee_education_subject" text,
  "employee_education_starting_date" text,
  "employee_education_complete_date" text,
  "employee_education_degree" text,
  "employee_education_grade" text,
  "employee_experience_company_name" text,
  "employee_experience_company_location" text,
  "employee_experience_company_job_position" text,
  "employee_experience_company_period_from" text,
  "employee_experience_company_period_to" text,
  "employee_department_id" integer NOT NULL,
  "employee_reports_to_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "employee_employeedocument" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "experience_letter" text,
  "offer_letter" text,
  "education_certificate" text,
  "skill_certificate" text,
  "created_at" timestamptz NOT NULL,
  "employee_id" integer NOT NULL,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "employee_entries" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" text,
  "start_time" timestamptz NOT NULL,
  "end_time" timestamptz NOT NULL,
  "created_date" date NOT NULL,
  "project" text,
  "activity" text,
  "assigned_to_id" integer,
  "user_id" integer,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "employee_post" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "experience_letter" text,
  "offer_letter" text,
  "education_certificate" text,
  "skill_certificate" text,
  "date_posted" timestamptz NOT NULL,
  "user_id" integer,
  "tenant_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "leave_balanceleaves" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "balancedays" integer,
  "created" timestamptz,
  "user_id" integer,
  "leaves_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "leave_leave" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "startdate" date,
  "enddate" date,
  "leavetype" text,
  "reason" text,
  "status" text NOT NULL,
  "is_approved" integer NOT NULL,
  "updated" timestamptz NOT NULL,
  "created" timestamptz NOT NULL,
  "user_id" integer,
  "description" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "management_invoice" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "client" text NOT NULL,
  "client_email" text,
  "billing_address" text,
  "date" date NOT NULL,
  "due_date" date,
  "project" text NOT NULL,
  "total_amount" numeric,
  "status" integer NOT NULL,
  "company_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "management_lineitem" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "service" text NOT NULL,
  "description" text NOT NULL,
  "quantity" integer NOT NULL,
  "rate" numeric NOT NULL,
  "amount" numeric NOT NULL,
  "client_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "manager_leave_balanceleave" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "balancedays" integer,
  "created" timestamptz,
  "user_id" integer,
  "leaves_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "manager_leave_managerleave" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "startdate" date,
  "enddate" date,
  "leavetype" text,
  "reason" text,
  "status" text NOT NULL,
  "is_approved" integer NOT NULL,
  "updated" timestamptz NOT NULL,
  "created" timestamptz NOT NULL,
  "user_id" integer,
  "description" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "manager_resign_managerresign" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "startdate" date,
  "reason" text,
  "status" text NOT NULL,
  "is_approved" integer NOT NULL,
  "updated" timestamptz NOT NULL,
  "created" timestamptz NOT NULL,
  "user_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "manageregularization_mregularization" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "check_in" timestamptz,
  "check_out" timestamptz,
  "reason" text,
  "status" text NOT NULL,
  "is_approved" integer NOT NULL,
  "updated" timestamptz NOT NULL,
  "created" timestamptz NOT NULL,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "managerpayroll_salary" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "month" date NOT NULL,
  "basic" integer NOT NULL,
  "da_percent" integer,
  "hra_percent" integer,
  "conveyance" integer,
  "bonuses" integer,
  "allowance" integer,
  "medical_allowance" integer,
  "tds" integer,
  "esi" integer,
  "providence_fund" integer,
  "leave" integer,
  "tax" integer,
  "labour_welfare" integer,
  "loan_repayment" integer,
  "others" integer,
  "manager_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "managers_employeenotification" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "notifications" text NOT NULL,
  "is_read" integer NOT NULL,
  "user_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "managers_manager" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "manager_first_name" text NOT NULL,
  "manager_last_name" text NOT NULL,
  "manager_email" text NOT NULL,
  "manager_joining_date" date NOT NULL,
  "manager_designation" text NOT NULL,
  "manager_id" text NOT NULL,
  "manager_phone" text,
  "manager_salary" text NOT NULL,
  "manager_birth_date" text,
  "manager_gender" text,
  "manager_father" text,
  "manager_mother" text,
  "manager_address" text,
  "manager_pin_code" text,
  "manager_state" text,
  "manager_country" text,
  "manager_image" text NOT NULL,
  "manager_created_date" timestamptz NOT NULL,
  "manager_status" text NOT NULL,
  "manager_tel" text,
  "manager_nationality" text,
  "manager_religion" text,
  "manager_marital_status" text,
  "manager_emergency_primary_name" text,
  "manager_emergency_primary_relationship" text,
  "manager_emergency_primary_phone1" text,
  "manager_emergency_primary_phone2" text,
  "manager_education_institution" text,
  "manager_education_subject" text,
  "manager_education_starting_date" text,
  "manager_education_complete_date" text,
  "manager_education_degree" text,
  "manager_education_grade" text,
  "manager_experience_company_name" text,
  "manager_experience_company_location" text,
  "manager_experience_company_job_position" text,
  "manager_experience_company_period_from" text,
  "manager_experience_company_period_to" text,
  "manager_department_id" integer,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "managers_managerattendance" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "check_in" timestamptz NOT NULL,
  "check_out" timestamptz,
  "manager_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "managers_managerentry" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "start_time" timestamptz NOT NULL,
  "end_time" timestamptz NOT NULL,
  "project" text,
  "activity" text,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "managers_managerpost" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "experience_letter" text,
  "offer_letter" text,
  "education_certificate" text,
  "skill_certificate" text,
  "date_posted" timestamptz NOT NULL,
  "user_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "payroll_salary" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "month" date NOT NULL,
  "basic" integer NOT NULL,
  "da_percent" integer,
  "hra_percent" integer,
  "conveyance" integer,
  "bonuses" integer,
  "allowance" integer,
  "medical_allowance" integer,
  "tds" integer,
  "esi" integer,
  "providence_fund" integer,
  "leave" integer,
  "tax" integer,
  "labour_welfare" integer,
  "loan_repayment" integer,
  "others" integer,
  "employee_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "regularization_regularization" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "check_in" timestamptz,
  "check_out" timestamptz,
  "reason" text,
  "status" text NOT NULL,
  "is_approved" integer NOT NULL,
  "updated" timestamptz NOT NULL,
  "created" timestamptz NOT NULL,
  "r_assigned_to_id" integer,
  "user_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "resign_resign" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "startdate" date,
  "reason" text,
  "status" text NOT NULL,
  "is_approved" integer NOT NULL,
  "updated" timestamptz NOT NULL,
  "created" timestamptz NOT NULL,
  "assigned_too_id" integer,
  "user_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "tenants" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "subdomain" text,
  "sales_email" text NOT NULL,
  "sales_phone" text,
  "status" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "settings" jsonb NOT NULL,
  PRIMARY KEY ("id")
);
