/**
 * Phase 4: Actionable Dashboard TypeScript Types
 * Comprehensive types for metrics, insights, recommendations, anomalies, and forecasts
 *
 * @module dashboard
 */

// ═════════════════════════════════════════════════════════════════════════════
// ENUMS
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Supported metric types for dashboard calculations
 */
export enum MetricType {
  CONVERSION_RATE = 'conversion_rate',
  AVG_DEAL_SIZE = 'avg_deal_size',
  PIPELINE_VALUE = 'pipeline_value',
  SALES_VELOCITY = 'sales_velocity',
  WIN_LOSS_RATE = 'win_loss_rate',
  RESPONSE_RATE = 'response_rate',
  FOLLOW_UP_RATE = 'follow_up_rate',
  TEAM_PERFORMANCE = 'team_performance',
  FORECAST_ACCURACY = 'forecast_accuracy',
  ACTIVITY_RATE = 'activity_rate',
  LEAD_QUALITY_SCORE = 'lead_quality_score',
}

/**
 * Types of insights generated by the system
 */
export enum InsightType {
  BOTTLENECK = 'bottleneck',
  PERFORMANCE = 'performance',
  FORECAST = 'forecast',
  ANOMALY = 'anomaly',
  TREND = 'trend',
  HEALTH = 'health',
  RECOMMENDATION = 'recommendation',
}

/**
 * Types of anomalies that can be detected
 */
export enum AnomalyType {
  UNUSUAL_ACTIVITY = 'unusual_activity',
  PERFORMANCE_DROP = 'performance_drop',
  SPIKE = 'spike',
  DATA_QUALITY = 'data_quality',
  PATTERN_BREAK = 'pattern_break',
  THRESHOLD_BREACH = 'threshold_breach',
}

/**
 * Severity levels for anomalies and alerts
 */
export enum Severity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

/**
 * Priority levels for recommendations and alerts
 */
export enum Priority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

/**
 * Effort levels for implementing recommendations
 */
export enum EffortLevel {
  TRIVIAL = 'trivial',
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
}

/**
 * Status of recommendations
 */
export enum RecommendationStatus {
  SUGGESTED = 'suggested',
  ACCEPTED = 'accepted',
  REJECTED = 'rejected',
  IMPLEMENTED = 'implemented',
  ARCHIVED = 'archived',
}

/**
 * Types of actions that can be recommended
 */
export enum ActionType {
  FOLLOW_UP_CALL = 'follow_up_call',
  SEND_EMAIL = 'send_email',
  REASSIGN_LEAD = 'reassign_lead',
  RE_QUALIFY = 're_qualify',
  CREATE_TASK = 'create_task',
  ADJUST_STRATEGY = 'adjust_strategy',
  UPDATE_TIMELINE = 'update_timeline',
  INVESTIGATE = 'investigate',
}

/**
 * Forecast types
 */
export enum ForecastType {
  REVENUE = 'revenue',
  DEALS_CLOSED = 'deals_closed',
  CONVERSION_RATE = 'conversion_rate',
  PIPELINE_VALUE = 'pipeline_value',
  VELOCITY = 'velocity',
}

/**
 * Forecast periods
 */
export enum ForecastPeriod {
  WEEK = 'week',
  MONTH = 'month',
  QUARTER = 'quarter',
  YEAR = 'year',
}

/**
 * Types of events in the dashboard audit trail
 */
export enum DashboardEventType {
  INSIGHT_GENERATED = 'insight_generated',
  INSIGHT_DISMISSED = 'insight_dismissed',
  RECOMMENDATION_SUGGESTED = 'recommendation_suggested',
  RECOMMENDATION_IMPLEMENTED = 'recommendation_implemented',
  ANOMALY_DETECTED = 'anomaly_detected',
  FORECAST_GENERATED = 'forecast_generated',
  METRIC_UPDATED = 'metric_updated',
  ALERT_TRIGGERED = 'alert_triggered',
}

/**
 * Log levels for insight processing logs
 */
export enum LogLevel {
  DEBUG = 'debug',
  INFO = 'info',
  WARNING = 'warning',
  ERROR = 'error',
}

/**
 * Trend direction indicators
 */
export enum Trend {
  UP = 'up',
  DOWN = 'down',
  NEUTRAL = 'neutral',
}

// ═════════════════════════════════════════════════════════════════════════════
// METRIC TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Core metric data interface
 */
export interface Metric {
  id: string;
  businessId: string;
  pipelineId?: string;

  // Identification
  metricType: MetricType;
  metricKey: string;
  metricLabel: string;

  // Values
  currentValue: number;
  previousValue?: number;
  targetValue?: number;
  periodStartDate: Date;
  periodEndDate: Date;

  // Metadata
  unit: string;
  trend: Trend;
  trendPercentage?: number;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Metric display card data
 */
export interface MetricCard extends Metric {
  sparklineData?: Array<{ date: Date; value: number }>;
  isGood?: boolean;
  isWarning?: boolean;
}

// ═════════════════════════════════════════════════════════════════════════════
// INSIGHT TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Supporting metrics for an insight
 */
export interface SupportingMetric {
  metricKey: string;
  label: string;
  value: number;
  unit: string;
  change?: number;
}

/**
 * Historical context for insights
 */
export interface InsightHistoricalContext {
  previousValue?: number;
  averageValue?: number;
  previousInsightDate?: Date;
  trendDuration?: string;
  pattern?: string;
}

/**
 * Base insight interface
 */
export interface BaseInsight {
  id: string;
  businessId: string;
  pipelineId?: string;
  insightType: InsightType;
  title: string;
  description: string;
  impactScore?: number;

  // AI metadata
  aiGenerated: boolean;
  aiModel?: string;
  confidenceScore?: number;

  // Data
  data: Record<string, unknown>;
  rootCause?: string;
  supportingMetrics?: SupportingMetric[];
  historicalContext?: InsightHistoricalContext;

  // User interaction
  dismissed: boolean;
  dismissedAt?: Date;
  dismissedBy?: string;
  actionTaken: boolean;
  actionTakenAt?: Date;
  actionDetails?: Record<string, unknown>;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Bottleneck insight - identifies stages where leads are stuck
 */
export interface BottleneckInsight extends BaseInsight {
  insightType: InsightType.BOTTLENECK;
  data: {
    stagedId: string;
    stageName: string;
    dealsStuck: number;
    avgDaysStuck: number;
    conversionRate: number;
    healthScore: number;
  };
}

/**
 * Performance insight - compares actual to target metrics
 */
export interface PerformanceInsight extends BaseInsight {
  insightType: InsightType.PERFORMANCE;
  data: {
    metricType: MetricType;
    actual: number;
    target: number;
    variance: number;
    variancePercent: number;
    period: string;
  };
}

/**
 * Forecast insight - predicts future performance
 */
export interface ForecastInsight extends BaseInsight {
  insightType: InsightType.FORECAST;
  data: {
    forecastType: ForecastType;
    predictedValue: number;
    lowerBound: number;
    upperBound: number;
    confidenceLevel: number;
    forecastPeriod: ForecastPeriod;
  };
}

/**
 * Anomaly insight - flags unusual patterns or values
 */
export interface AnomalyInsight extends BaseInsight {
  insightType: InsightType.ANOMALY;
  data: {
    anomalyType: AnomalyType;
    severity: Severity;
    baselineValue: number;
    detectedValue: number;
    deviationPercent: number;
    standardDeviations: number;
    likelyCauses: string[];
  };
}

/**
 * Trend insight - analyzes patterns over time
 */
export interface TrendInsight extends BaseInsight {
  insightType: InsightType.TREND;
  data: {
    metricType: MetricType;
    direction: Trend;
    percentChange: number;
    period: string;
    seasonalPattern?: string;
    forecastedDirection?: Trend;
  };
}

/**
 * Health insight - assesses overall business health
 */
export interface HealthInsight extends BaseInsight {
  insightType: InsightType.HEALTH;
  data: {
    overallHealthScore: number;
    scoreBreakdown: Record<string, number>;
    riskFactors: string[];
    opportunityFactors: string[];
  };
}

/**
 * Recommendation insight - suggests actions
 */
export interface RecommendationInsight extends BaseInsight {
  insightType: InsightType.RECOMMENDATION;
  data: {
    recommendedActions: string[];
    expectedOutcome: string;
    timelineForAction: string;
  };
}

/**
 * Discriminated union of all insight types
 */
export type Insight =
  | BottleneckInsight
  | PerformanceInsight
  | ForecastInsight
  | AnomalyInsight
  | TrendInsight
  | HealthInsight
  | RecommendationInsight;

// ═════════════════════════════════════════════════════════════════════════════
// RECOMMENDATION TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Implementation details for a recommendation
 */
export interface RecommendationImplementation {
  status: RecommendationStatus;
  implementedAt?: Date;
  implementedBy?: string;
  feedback?: {
    score: number; // 1-5
    comment?: string;
  };
  relatedEntities?: string[];
  parameters?: Record<string, unknown>;
}

/**
 * Recommendation interface
 */
export interface Recommendation {
  id: string;
  businessId: string;
  insightId?: string;

  // Content
  title: string;
  description: string;
  actionType: ActionType;

  // Priority & impact
  priority: Priority;
  expectedImpact?: string;
  effortLevel?: EffortLevel;

  // AI metadata
  confidenceScore: number;
  reasoning?: string;

  // Implementation
  implementation: RecommendationImplementation;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Recommendation with full insight context
 */
export interface RecommendationWithInsight extends Recommendation {
  insight?: Insight;
}

// ═════════════════════════════════════════════════════════════════════════════
// ANOMALY TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Anomaly resolution details
 */
export interface AnomalyResolution {
  acknowledged: boolean;
  acknowledgedAt?: Date;
  acknowledgedBy?: string;
  resolved: boolean;
  resolvedAt?: Date;
  resolutionNotes?: string;
}

/**
 * Anomaly interface
 */
export interface Anomaly {
  id: string;
  businessId: string;

  // Identification
  anomalyType: AnomalyType;
  affectedMetric: string;
  affectedEntities?: string[];

  // Details
  description: string;
  severity: Severity;
  baselineValue?: number;
  detectedValue?: number;
  deviationPercent?: number;

  // Detection
  detectionMethod: string;
  standardDeviations?: number;
  confidenceScore: number;
  likelyCauses?: string[];

  // Resolution
  resolution: AnomalyResolution;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

// ═════════════════════════════════════════════════════════════════════════════
// FORECAST TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Forecast actual values (populated after forecast period)
 */
export interface ForecastActual {
  value?: number;
  recordedAt?: Date;
  accuracyError?: number;
}

/**
 * Forecast interface
 */
export interface Forecast {
  id: string;
  businessId: string;
  pipelineId?: string;

  // Metadata
  forecastType: ForecastType;
  forecastPeriod: ForecastPeriod;

  // Window
  forecastStartDate: Date;
  forecastEndDate: Date;
  generatedAt: Date;

  // Values
  predictedValue: number;
  lowerBound?: number;
  upperBound?: number;
  confidenceLevel: number;

  // Model
  modelType: string;
  trainingDataPoints?: number;
  modelAccuracy?: number;

  // Actual (after forecast period ends)
  actual?: ForecastActual;

  // Factors
  keyFactors?: Record<string, unknown>;
  assumptions?: string;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

// ═════════════════════════════════════════════════════════════════════════════
// EVENT & LOG TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Dashboard event (audit trail)
 */
export interface DashboardEvent {
  id: string;
  businessId: string;

  eventType: DashboardEventType;

  // References
  insightId?: string;
  recommendationId?: string;
  anomalyId?: string;
  forecastId?: string;

  // User
  userId?: string;
  details?: Record<string, unknown>;

  // Timestamp
  createdAt: Date;
}

/**
 * Insight processing log
 */
export interface InsightLog {
  id: string;
  businessId: string;
  insightId?: string;

  logLevel: LogLevel;
  message: string;
  context?: Record<string, unknown>;

  errorType?: string;
  errorStack?: string;

  createdAt: Date;
}

// ═════════════════════════════════════════════════════════════════════════════
// ALERT CONFIGURATION TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Alert trigger condition
 */
export type AlertTriggerCondition =
  | 'above_threshold'
  | 'below_threshold'
  | 'equals'
  | 'deviates_by_percent'
  | 'deviates_by_std_dev';

/**
 * Alert notification method
 */
export type NotificationMethod = 'email' | 'in_app' | 'sms' | 'slack';

/**
 * Alert configuration interface
 */
export interface AlertConfiguration {
  id: string;
  businessId: string;

  // Configuration
  alertName: string;
  alertType: AnomalyType;
  metricType: string;
  description?: string;

  // Trigger
  triggerCondition: AlertTriggerCondition;
  thresholdValue?: number;
  deviationPercent?: number;
  stdDevCount?: number;

  // Severity
  severity: Severity;

  // Notifications
  notifyUsers?: string[];
  notificationMethods: NotificationMethod[];
  enableEmailNotifications: boolean;
  enableInAppNotifications: boolean;

  // Status
  enabled: boolean;
  createdBy?: string;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

// ═════════════════════════════════════════════════════════════════════════════
// DASHBOARD STATE TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Dashboard KPI summary for home view
 */
export interface DashboardKPISummary {
  totalPipelineValue: number;
  conversionRate: number;
  averageDealSize: number;
  salesVelocity: number;
  trend: {
    pipelineValue: Trend;
    conversionRate: Trend;
    dealSize: Trend;
    velocity: Trend;
  };
  previousPeriodComparison: {
    pipelineValueChange: number;
    conversionRateChange: number;
    dealSizeChange: number;
    velocityChange: number;
  };
}

/**
 * Dashboard health indicator
 */
export interface DashboardHealth {
  overallScore: number;
  status: 'excellent' | 'good' | 'fair' | 'poor';
  componentScores: {
    pipelineHealth: number;
    teamPerformance: number;
    dataQuality: number;
    forecastAccuracy: number;
  };
  alerts: Anomaly[];
  recommendations: Recommendation[];
}

/**
 * Complete dashboard state
 */
export interface DashboardState {
  kpiSummary: DashboardKPISummary;
  health: DashboardHealth;
  recentInsights: Insight[];
  activeRecommendations: Recommendation[];
  pendingAnomalies: Anomaly[];
  forecasts: Forecast[];
  metrics: Metric[];
  isLoading: boolean;
  error?: string;
  lastUpdated: Date;
}

// ═════════════════════════════════════════════════════════════════════════════
// API REQUEST/RESPONSE TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Request to generate insights
 */
export interface GenerateInsightRequest {
  pipelineId?: string;
  insightType?: InsightType;
  metricTypes?: MetricType[];
  days?: number;
}

/**
 * Response with generated insights
 */
export interface GenerateInsightResponse {
  insights: Insight[];
  generatedAt: Date;
  processingTimeMs: number;
}

/**
 * Request to get recommendations
 */
export interface GetRecommendationsRequest {
  status?: RecommendationStatus;
  priority?: Priority;
  limit?: number;
  offset?: number;
}

/**
 * Response with recommendations
 */
export interface GetRecommendationsResponse {
  recommendations: Recommendation[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * Request to detect anomalies
 */
export interface DetectAnomaliesRequest {
  metricType?: string;
  stdDevThreshold?: number;
  days?: number;
}

/**
 * Response with detected anomalies
 */
export interface DetectAnomaliesResponse {
  anomalies: Anomaly[];
  detectionTimeMs: number;
}

/**
 * Request to generate forecasts
 */
export interface GenerateForecastRequest {
  forecastType: ForecastType;
  forecastPeriod: ForecastPeriod;
  pipelineId?: string;
}

/**
 * Response with forecasts
 */
export interface GenerateForecastResponse {
  forecasts: Forecast[];
  generatedAt: Date;
  modelInfo: {
    type: string;
    accuracy?: number;
  };
}

// ═════════════════════════════════════════════════════════════════════════════
// COMPONENT PROP TYPES
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Props for metric display components
 */
export interface MetricCardProps {
  metric: MetricCard;
  onClick?: (metric: Metric) => void;
  size?: 'small' | 'medium' | 'large';
  showSparkline?: boolean;
  showTrend?: boolean;
}

/**
 * Props for insight components
 */
export interface InsightCardProps {
  insight: Insight;
  onDismiss?: (insightId: string) => void;
  onTakeAction?: (insightId: string) => void;
  showDetails?: boolean;
}

/**
 * Props for recommendation components
 */
export interface RecommendationCardProps {
  recommendation: Recommendation;
  onImplement?: (recommendationId: string) => void;
  onDismiss?: (recommendationId: string) => void;
  onFeedback?: (recommendationId: string, feedback: { score: number; comment?: string }) => void;
  expanded?: boolean;
}

/**
 * Props for anomaly alert components
 */
export interface AnomalyAlertProps {
  anomaly: Anomaly;
  onAcknowledge?: (anomalyId: string) => void;
  onInvestigate?: (anomalyId: string) => void;
  onResolve?: (anomalyId: string, resolution: string) => void;
}
