export interface StylePreset {
  id: string;
  name: string;
  tagline: string;
  primary: string;
  accent: string;
  bg: string;
  surface: string;
  textPrimary: string;
  textSecondary: string;
  theme: 'light' | 'dark';
  font: 'modern' | 'classic' | 'bold' | 'elegant' | 'playful' | 'tech';
  layout: 'card' | 'hero' | 'grid' | 'minimal' | 'magazine' | 'list';
  buttonStyle: 'rounded' | 'pill' | 'square';
  mood: string;
  gradFrom: string;
  gradTo: string;
  tag?: string;
}

export interface CategoryInfo {
  emoji: string;
  label: string;
  description: string;
  bgColor: string;
  gradFrom: string;
  gradTo: string;
  presets: StylePreset[];
}

export const categoryData: Record<string, CategoryInfo> = {
  Retail: {
    emoji: '🛍️',
    label: 'Retail',
    description: 'Shopping & Products',
    bgColor: '#FFF7ED',
    gradFrom: '#F97316',
    gradTo: '#FBBF24',
    presets: [
      {
        id: 'retail-urban',
        name: 'Urban Boutique',
        tagline: 'Sleek, dark, and product-first',
        primary: '#1C1C2E',
        accent: '#FF4F7B',
        bg: '#F9F9FC',
        surface: '#FFFFFF',
        textPrimary: '#1C1C2E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'grid',
        buttonStyle: 'square',
        mood: '✨ Minimal & Sleek',
        gradFrom: '#1C1C2E',
        gradTo: '#FF4F7B',
        tag: 'Popular',
      },
      {
        id: 'retail-bold',
        name: 'Bold Commerce',
        tagline: 'Eye-catching, energetic, trendy',
        primary: '#FF6B35',
        accent: '#1C1C2E',
        bg: '#FFFFFF',
        surface: '#FFF8F5',
        textPrimary: '#1C1C2E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'rounded',
        mood: '🔥 Bold & Vibrant',
        gradFrom: '#FF6B35',
        gradTo: '#F97316',
      },
      {
        id: 'retail-luxury',
        name: 'Classic Luxe',
        tagline: 'Premium, elegant, timeless',
        primary: '#B8960C',
        accent: '#1C1C2E',
        bg: '#FAFAF5',
        surface: '#FFFFF0',
        textPrimary: '#1C1C2E',
        textSecondary: '#78716C',
        theme: 'light',
        font: 'elegant',
        layout: 'magazine',
        buttonStyle: 'pill',
        mood: '👑 Luxury & Refined',
        gradFrom: '#B8960C',
        gradTo: '#D4AF37',
      },
      {
        id: 'retail-neon',
        name: 'Neon Market',
        tagline: 'Dark, futuristic, electric',
        primary: '#00D4FF',
        accent: '#FF00FF',
        bg: '#0A0A1A',
        surface: '#1A1A2E',
        textPrimary: '#FFFFFF',
        textSecondary: '#A0AEC0',
        theme: 'dark',
        font: 'tech',
        layout: 'grid',
        buttonStyle: 'pill',
        mood: '⚡ Electric & Bold',
        gradFrom: '#00D4FF',
        gradTo: '#FF00FF',
        tag: 'Trending',
      },
    ],
  },

  Restaurant: {
    emoji: '🍽️',
    label: 'Restaurant',
    description: 'Food & Dining',
    bgColor: '#FFF1F0',
    gradFrom: '#EF4444',
    gradTo: '#F97316',
    presets: [
      {
        id: 'restaurant-rustic',
        name: 'Rustic Kitchen',
        tagline: 'Warm, homey, and inviting',
        primary: '#8B4513',
        accent: '#FFB347',
        bg: '#FDF5E6',
        surface: '#FFF8F0',
        textPrimary: '#3D1C02',
        textSecondary: '#78716C',
        theme: 'light',
        font: 'classic',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '🏡 Warm & Cozy',
        gradFrom: '#8B4513',
        gradTo: '#FFB347',
        tag: 'Popular',
      },
      {
        id: 'restaurant-modern',
        name: 'Modern Bistro',
        tagline: 'Charcoal, fresh, contemporary',
        primary: '#2D2D2D',
        accent: '#A8E063',
        bg: '#FFFFFF',
        surface: '#F8F8F8',
        textPrimary: '#1A1A1A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🌿 Fresh & Modern',
        gradFrom: '#2D2D2D',
        gradTo: '#A8E063',
      },
      {
        id: 'restaurant-street',
        name: 'Street Food Vibes',
        tagline: 'Bold, fun, and fast',
        primary: '#DC143C',
        accent: '#FFD700',
        bg: '#FFFFFF',
        surface: '#FFF9F0',
        textPrimary: '#1A1A1A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'grid',
        buttonStyle: 'pill',
        mood: '🌶️ Spicy & Fun',
        gradFrom: '#DC143C',
        gradTo: '#FFD700',
      },
      {
        id: 'restaurant-fine',
        name: 'Fine Dining',
        tagline: 'Midnight elegance, gold accents',
        primary: '#C8A951',
        accent: '#F5F5F0',
        bg: '#1A1A2E',
        surface: '#252535',
        textPrimary: '#F5F5F0',
        textSecondary: '#C8A951',
        theme: 'dark',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'pill',
        mood: '✦ Fine & Elegant',
        gradFrom: '#1A1A2E',
        gradTo: '#C8A951',
        tag: 'Premium',
      },
    ],
  },

  'Salon & Spa': {
    emoji: '💆',
    label: 'Salon & Spa',
    description: 'Beauty & Wellness',
    bgColor: '#FFF0F5',
    gradFrom: '#EC4899',
    gradTo: '#F9A8D4',
    presets: [
      {
        id: 'salon-rose',
        name: 'Rose Petal',
        tagline: 'Soft, feminine, luxurious',
        primary: '#C8737A',
        accent: '#C9A96E',
        bg: '#FFF5F7',
        surface: '#FFFAFA',
        textPrimary: '#3D1A20',
        textSecondary: '#9A7070',
        theme: 'light',
        font: 'elegant',
        layout: 'card',
        buttonStyle: 'pill',
        mood: '🌸 Soft & Romantic',
        gradFrom: '#C8737A',
        gradTo: '#C9A96E',
        tag: 'Popular',
      },
      {
        id: 'salon-zen',
        name: 'Zen Garden',
        tagline: 'Sage, calm, and balanced',
        primary: '#6B8F71',
        accent: '#C8A951',
        bg: '#F5F5EF',
        surface: '#FAFAF5',
        textPrimary: '#1A2E1C',
        textSecondary: '#6B7A6B',
        theme: 'light',
        font: 'classic',
        layout: 'minimal',
        buttonStyle: 'pill',
        mood: '🍃 Calm & Natural',
        gradFrom: '#6B8F71',
        gradTo: '#C8A951',
      },
      {
        id: 'salon-glamour',
        name: 'Glamour Night',
        tagline: 'Deep purple, champagne, dramatic',
        primary: '#7B2D8B',
        accent: '#C9A96E',
        bg: '#1A0A2E',
        surface: '#2D1A3E',
        textPrimary: '#F5F0FF',
        textSecondary: '#C9A96E',
        theme: 'dark',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '💜 Glam & Bold',
        gradFrom: '#7B2D8B',
        gradTo: '#C9A96E',
        tag: 'Trending',
      },
      {
        id: 'salon-urban',
        name: 'Urban Beauty',
        tagline: 'Dark slate with mint accents',
        primary: '#2D3A4A',
        accent: '#5DDED6',
        bg: '#F5F7FA',
        surface: '#FFFFFF',
        textPrimary: '#1A252F',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '🌊 Clean & Chic',
        gradFrom: '#2D3A4A',
        gradTo: '#5DDED6',
      },
    ],
  },

  'Fitness & Gym': {
    emoji: '💪',
    label: 'Fitness & Gym',
    description: 'Sports & Training',
    bgColor: '#EFF6FF',
    gradFrom: '#3B82F6',
    gradTo: '#1D4ED8',
    presets: [
      {
        id: 'fitness-power',
        name: 'Power Zone',
        tagline: 'Jet black with electric blue',
        primary: '#00BFFF',
        accent: '#FF4444',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#9CA3AF',
        theme: 'dark',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '⚡ Dark & Intense',
        gradFrom: '#0A0A0A',
        gradTo: '#00BFFF',
        tag: 'Popular',
      },
      {
        id: 'fitness-athletic',
        name: 'Athletic Edge',
        tagline: 'Clean white with bold red',
        primary: '#E53935',
        accent: '#1A1A1A',
        bg: '#FFFFFF',
        surface: '#F8F8F8',
        textPrimary: '#1A1A1A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'grid',
        buttonStyle: 'square',
        mood: '🏋️ Athletic & Clean',
        gradFrom: '#E53935',
        gradTo: '#B71C1C',
      },
      {
        id: 'fitness-neon',
        name: 'Neon Rush',
        tagline: 'Black with neon green energy',
        primary: '#39FF14',
        accent: '#00BFFF',
        bg: '#0A0A0A',
        surface: '#111111',
        textPrimary: '#FFFFFF',
        textSecondary: '#6B7280',
        theme: 'dark',
        font: 'tech',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🟢 Neon & Electric',
        gradFrom: '#39FF14',
        gradTo: '#00BFFF',
        tag: 'Trending',
      },
      {
        id: 'fitness-wellness',
        name: 'Wellness Flow',
        tagline: 'Calming blues, health-focused',
        primary: '#0077B6',
        accent: '#90E0EF',
        bg: '#F0F8FF',
        surface: '#FFFFFF',
        textPrimary: '#003D5B',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'pill',
        mood: '🌊 Calm & Healthy',
        gradFrom: '#0077B6',
        gradTo: '#90E0EF',
      },
    ],
  },

  Healthcare: {
    emoji: '🏥',
    label: 'Healthcare',
    description: 'Medical & Wellness',
    bgColor: '#F0FDFA',
    gradFrom: '#0D9488',
    gradTo: '#06B6D4',
    presets: [
      {
        id: 'health-clinical',
        name: 'Clinical Blue',
        tagline: 'Medical-grade clean and professional',
        primary: '#0077B6',
        accent: '#00B4D8',
        bg: '#F0F8FF',
        surface: '#FFFFFF',
        textPrimary: '#003D5B',
        textSecondary: '#4B6580',
        theme: 'light',
        font: 'classic',
        layout: 'list',
        buttonStyle: 'rounded',
        mood: '🔵 Professional & Clean',
        gradFrom: '#0077B6',
        gradTo: '#00B4D8',
        tag: 'Popular',
      },
      {
        id: 'health-warm',
        name: 'Warm Healing',
        tagline: 'Teal with warm orange accents',
        primary: '#00897B',
        accent: '#FF8A65',
        bg: '#F5FFFD',
        surface: '#FFFFFF',
        textPrimary: '#00352E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '💚 Warm & Caring',
        gradFrom: '#00897B',
        gradTo: '#FF8A65',
      },
      {
        id: 'health-modern',
        name: 'Modern Med',
        tagline: 'Slate purple, innovative feel',
        primary: '#5C6BC0',
        accent: '#AB47BC',
        bg: '#F8F9FF',
        surface: '#FFFFFF',
        textPrimary: '#1A1A3E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '🔬 Modern & Innovative',
        gradFrom: '#5C6BC0',
        gradTo: '#AB47BC',
        tag: 'Trending',
      },
      {
        id: 'health-gentle',
        name: 'Gentle Touch',
        tagline: 'Soft pastels, kind and welcoming',
        primary: '#42A5F5',
        accent: '#EC407A',
        bg: '#F5F9FF',
        surface: '#FFFFFF',
        textPrimary: '#1A2F4A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'card',
        buttonStyle: 'pill',
        mood: '🌷 Gentle & Welcoming',
        gradFrom: '#42A5F5',
        gradTo: '#EC407A',
      },
    ],
  },

  'Real Estate': {
    emoji: '🏠',
    label: 'Real Estate',
    description: 'Property & Homes',
    bgColor: '#F8FAFC',
    gradFrom: '#1E40AF',
    gradTo: '#3B82F6',
    presets: [
      {
        id: 'realestate-premier',
        name: 'Premier Estate',
        tagline: 'Navy and gold, absolutely premium',
        primary: '#1A237E',
        accent: '#C8A951',
        bg: '#FAFAF5',
        surface: '#FFFFFF',
        textPrimary: '#0D1A5E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'elegant',
        layout: 'magazine',
        buttonStyle: 'square',
        mood: '🏛️ Premium & Prestige',
        gradFrom: '#1A237E',
        gradTo: '#C8A951',
        tag: 'Popular',
      },
      {
        id: 'realestate-modern',
        name: 'Urban Realty',
        tagline: 'Charcoal with bold red, sharp',
        primary: '#263238',
        accent: '#F44336',
        bg: '#FFFFFF',
        surface: '#F8F8F8',
        textPrimary: '#1A1A1A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🏙️ Bold & Modern',
        gradFrom: '#263238',
        gradTo: '#F44336',
      },
      {
        id: 'realestate-eco',
        name: 'Green Homes',
        tagline: 'Forest green, eco-conscious',
        primary: '#2E7D32',
        accent: '#A5D6A7',
        bg: '#F5FFF5',
        surface: '#FFFFFF',
        textPrimary: '#1B3D1C',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '🌿 Eco & Natural',
        gradFrom: '#2E7D32',
        gradTo: '#A5D6A7',
      },
      {
        id: 'realestate-black',
        name: 'Black Pearl',
        tagline: 'Black background, gold luxury',
        primary: '#C8A951',
        accent: '#FFFFFF',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#C8A951',
        theme: 'dark',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'pill',
        mood: '⭐ Exclusive & Luxury',
        gradFrom: '#0A0A0A',
        gradTo: '#C8A951',
        tag: 'Premium',
      },
    ],
  },

  Education: {
    emoji: '📚',
    label: 'Education',
    description: 'Learning & Coaching',
    bgColor: '#FAF5FF',
    gradFrom: '#7C3AED',
    gradTo: '#A78BFA',
    presets: [
      {
        id: 'edu-bright',
        name: 'Bright Academy',
        tagline: 'Blue and yellow, energetic learning',
        primary: '#1565C0',
        accent: '#FFC107',
        bg: '#F0F4FF',
        surface: '#FFFFFF',
        textPrimary: '#0D2060',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '📖 Bright & Engaging',
        gradFrom: '#1565C0',
        gradTo: '#FFC107',
        tag: 'Popular',
      },
      {
        id: 'edu-creative',
        name: 'Creative Campus',
        tagline: 'Purple and orange, inspiring',
        primary: '#7B1FA2',
        accent: '#FF7043',
        bg: '#FAF5FF',
        surface: '#FFFFFF',
        textPrimary: '#3A0063',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '🎨 Creative & Fun',
        gradFrom: '#7B1FA2',
        gradTo: '#FF7043',
      },
      {
        id: 'edu-tech',
        name: 'Cyber School',
        tagline: 'Dark with teal, tech-forward',
        primary: '#00BFA5',
        accent: '#00E5FF',
        bg: '#0D1117',
        surface: '#161B22',
        textPrimary: '#E6EDF3',
        textSecondary: '#8B949E',
        theme: 'dark',
        font: 'tech',
        layout: 'list',
        buttonStyle: 'square',
        mood: '💻 Tech & Future',
        gradFrom: '#006064',
        gradTo: '#00BFA5',
        tag: 'Trending',
      },
      {
        id: 'edu-classic',
        name: 'Classic Hall',
        tagline: 'Navy and maroon, traditional',
        primary: '#1A237E',
        accent: '#B71C1C',
        bg: '#FAF9F5',
        surface: '#FFFFFF',
        textPrimary: '#0D1A5E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'classic',
        layout: 'magazine',
        buttonStyle: 'square',
        mood: '🎓 Traditional & Trusted',
        gradFrom: '#1A237E',
        gradTo: '#B71C1C',
      },
    ],
  },

  Consulting: {
    emoji: '💼',
    label: 'Consulting',
    description: 'Advisory & Strategy',
    bgColor: '#F8FAFC',
    gradFrom: '#1E3A5F',
    gradTo: '#2563EB',
    presets: [
      {
        id: 'consulting-executive',
        name: 'Executive Suite',
        tagline: 'Navy and gold, authority and trust',
        primary: '#1A237E',
        accent: '#C8A951',
        bg: '#FAFAF5',
        surface: '#FFFFFF',
        textPrimary: '#0D1A5E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'square',
        mood: '🏆 Authoritative & Premium',
        gradFrom: '#1A237E',
        gradTo: '#C8A951',
        tag: 'Popular',
      },
      {
        id: 'consulting-strategy',
        name: 'Strategy Edge',
        tagline: 'Charcoal and teal, sharp and clear',
        primary: '#263238',
        accent: '#00BCD4',
        bg: '#F5FFFE',
        surface: '#FFFFFF',
        textPrimary: '#1A1A2E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '📊 Strategic & Focused',
        gradFrom: '#263238',
        gradTo: '#00BCD4',
      },
      {
        id: 'consulting-innovation',
        name: 'Innovation Hub',
        tagline: 'Deep purple, forward-thinking',
        primary: '#6A1B9A',
        accent: '#E1BEE7',
        bg: '#FAF5FF',
        surface: '#FFFFFF',
        textPrimary: '#3A0063',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'rounded',
        mood: '💡 Innovative & Bold',
        gradFrom: '#6A1B9A',
        gradTo: '#AB47BC',
        tag: 'Trending',
      },
      {
        id: 'consulting-bold',
        name: 'Bold Advisory',
        tagline: 'Deep red and dark, decisive',
        primary: '#B71C1C',
        accent: '#1A1A2E',
        bg: '#FFFFFF',
        surface: '#F8F8F8',
        textPrimary: '#1A1A1A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🔴 Bold & Decisive',
        gradFrom: '#B71C1C',
        gradTo: '#E53935',
      },
    ],
  },

  'E-commerce': {
    emoji: '🛒',
    label: 'E-commerce',
    description: 'Online Store',
    bgColor: '#F0FDF4',
    gradFrom: '#16A34A',
    gradTo: '#4ADE80',
    presets: [
      {
        id: 'ecom-modern',
        name: 'Shop Modern',
        tagline: 'Blue and orange, conversion-focused',
        primary: '#1565C0',
        accent: '#FF7043',
        bg: '#F5F8FF',
        surface: '#FFFFFF',
        textPrimary: '#0D2060',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '🛍️ Modern & Conversion-Ready',
        gradFrom: '#1565C0',
        gradTo: '#FF7043',
        tag: 'Popular',
      },
      {
        id: 'ecom-dark',
        name: 'Dark Store',
        tagline: 'Black background, bold pop',
        primary: '#FF5722',
        accent: '#FFFFFF',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#9CA3AF',
        theme: 'dark',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🖤 Dark & Striking',
        gradFrom: '#0A0A0A',
        gradTo: '#FF5722',
        tag: 'Trending',
      },
      {
        id: 'ecom-vibrant',
        name: 'Vibrant Market',
        tagline: 'Purple and yellow, playful',
        primary: '#7B1FA2',
        accent: '#FFC107',
        bg: '#FAFAFF',
        surface: '#FFFFFF',
        textPrimary: '#3A0063',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'magazine',
        buttonStyle: 'pill',
        mood: '🌈 Vibrant & Fun',
        gradFrom: '#7B1FA2',
        gradTo: '#FFC107',
      },
      {
        id: 'ecom-eco',
        name: 'Eco Shop',
        tagline: 'Green and earthy, sustainable',
        primary: '#2E7D32',
        accent: '#795548',
        bg: '#F5FFF5',
        surface: '#FFFFFF',
        textPrimary: '#1B3D1C',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'classic',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '🌱 Eco & Conscious',
        gradFrom: '#2E7D32',
        gradTo: '#795548',
      },
    ],
  },

  Hospitality: {
    emoji: '🏨',
    label: 'Hospitality',
    description: 'Hotels & Travel',
    bgColor: '#FFFBEB',
    gradFrom: '#D97706',
    gradTo: '#F59E0B',
    presets: [
      {
        id: 'hotel-luxury',
        name: 'Luxury Suite',
        tagline: 'Gold on midnight, absolutely regal',
        primary: '#C8A951',
        accent: '#F5F5F0',
        bg: '#1A237E',
        surface: '#1E2A7E',
        textPrimary: '#F5F5F0',
        textSecondary: '#C8A951',
        theme: 'dark',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'pill',
        mood: '🌟 Regal & Opulent',
        gradFrom: '#1A237E',
        gradTo: '#C8A951',
        tag: 'Premium',
      },
      {
        id: 'hotel-boutique',
        name: 'Boutique Stay',
        tagline: 'Pink and charcoal, stylish',
        primary: '#AD1457',
        accent: '#263238',
        bg: '#FFF5F8',
        surface: '#FFFFFF',
        textPrimary: '#5A0028',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'elegant',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '🌸 Boutique & Chic',
        gradFrom: '#AD1457',
        gradTo: '#E91E63',
        tag: 'Popular',
      },
      {
        id: 'hotel-coastal',
        name: 'Coastal Resort',
        tagline: 'Teal and sand, breezy vibes',
        primary: '#006064',
        accent: '#FFB74D',
        bg: '#F0FFFF',
        surface: '#FFFFFF',
        textPrimary: '#00252A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '🌊 Coastal & Breezy',
        gradFrom: '#006064',
        gradTo: '#FFB74D',
      },
      {
        id: 'hotel-lodge',
        name: 'Mountain Lodge',
        tagline: 'Warm brown and cream, rustic',
        primary: '#5D4037',
        accent: '#FFF8E1',
        bg: '#FFF8F0',
        surface: '#FFFAF5',
        textPrimary: '#2E1503',
        textSecondary: '#78716C',
        theme: 'light',
        font: 'classic',
        layout: 'magazine',
        buttonStyle: 'rounded',
        mood: '🏔️ Rustic & Warm',
        gradFrom: '#5D4037',
        gradTo: '#A1887F',
      },
    ],
  },

  Photography: {
    emoji: '📷',
    label: 'Photography',
    description: 'Creative & Visual',
    bgColor: '#F5F3FF',
    gradFrom: '#6D28D9',
    gradTo: '#A78BFA',
    presets: [
      {
        id: 'photo-dark',
        name: 'Dark Studio',
        tagline: 'Black and red, dramatic impact',
        primary: '#F44336',
        accent: '#FFFFFF',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#9CA3AF',
        theme: 'dark',
        font: 'bold',
        layout: 'grid',
        buttonStyle: 'square',
        mood: '📸 Dramatic & Bold',
        gradFrom: '#0A0A0A',
        gradTo: '#F44336',
        tag: 'Popular',
      },
      {
        id: 'photo-minimal',
        name: 'Clean Frame',
        tagline: 'Near-black with gray, minimal art',
        primary: '#212121',
        accent: '#9E9E9E',
        bg: '#FFFFFF',
        surface: '#F5F5F5',
        textPrimary: '#121212',
        textSecondary: '#616161',
        theme: 'light',
        font: 'modern',
        layout: 'minimal',
        buttonStyle: 'square',
        mood: '⬜ Clean & Minimal',
        gradFrom: '#212121',
        gradTo: '#9E9E9E',
      },
      {
        id: 'photo-creative',
        name: 'Creative Pop',
        tagline: 'Purple and yellow, artistic',
        primary: '#7B1FA2',
        accent: '#FFC107',
        bg: '#FAFAFF',
        surface: '#FFFFFF',
        textPrimary: '#3A0063',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'magazine',
        buttonStyle: 'pill',
        mood: '🎨 Artistic & Creative',
        gradFrom: '#7B1FA2',
        gradTo: '#FFC107',
        tag: 'Trending',
      },
      {
        id: 'photo-film',
        name: 'Film Noir',
        tagline: 'Sepia gold on deep dark, timeless',
        primary: '#C8A951',
        accent: '#F5E6C8',
        bg: '#1A1212',
        surface: '#2A1A1A',
        textPrimary: '#F5E6C8',
        textSecondary: '#C8A951',
        theme: 'dark',
        font: 'elegant',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '🎞️ Cinematic & Timeless',
        gradFrom: '#1A1212',
        gradTo: '#C8A951',
        tag: 'Premium',
      },
    ],
  },

  'Finance & Legal': {
    emoji: '⚖️',
    label: 'Finance & Legal',
    description: 'Financial Services',
    bgColor: '#EEF2FF',
    gradFrom: '#1E3A8A',
    gradTo: '#3B82F6',
    presets: [
      {
        id: 'finance-trust',
        name: 'Trust Navy',
        tagline: 'Navy and gold, deeply trusted',
        primary: '#1A237E',
        accent: '#C8A951',
        bg: '#F5F7FF',
        surface: '#FFFFFF',
        textPrimary: '#0D1A5E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'classic',
        layout: 'list',
        buttonStyle: 'square',
        mood: '🏛️ Trustworthy & Solid',
        gradFrom: '#1A237E',
        gradTo: '#C8A951',
        tag: 'Popular',
      },
      {
        id: 'finance-growth',
        name: 'Green Growth',
        tagline: 'Dark green and charcoal, growth',
        primary: '#1B5E20',
        accent: '#66BB6A',
        bg: '#F5FFF5',
        surface: '#FFFFFF',
        textPrimary: '#0A2E0A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '📈 Growth-Focused',
        gradFrom: '#1B5E20',
        gradTo: '#66BB6A',
      },
      {
        id: 'finance-premium',
        name: 'Premium Dark',
        tagline: 'Copper on black, exclusive',
        primary: '#B87333',
        accent: '#FFFFFF',
        bg: '#1A1A1A',
        surface: '#2A2A2A',
        textPrimary: '#FFFFFF',
        textSecondary: '#B87333',
        theme: 'dark',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'square',
        mood: '💎 Exclusive & Premium',
        gradFrom: '#1A1A1A',
        gradTo: '#B87333',
        tag: 'Premium',
      },
      {
        id: 'finance-corporate',
        name: 'Corporate Edge',
        tagline: 'Slate and red, sharp decisions',
        primary: '#455A64',
        accent: '#D32F2F',
        bg: '#F5F7FA',
        surface: '#FFFFFF',
        textPrimary: '#1A2530',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'grid',
        buttonStyle: 'square',
        mood: '🔲 Sharp & Corporate',
        gradFrom: '#455A64',
        gradTo: '#D32F2F',
      },
    ],
  },

  Automotive: {
    emoji: '🚗',
    label: 'Automotive',
    description: 'Cars & Service',
    bgColor: '#FFF1F2',
    gradFrom: '#DC2626',
    gradTo: '#EF4444',
    presets: [
      {
        id: 'auto-speed',
        name: 'Speed Red',
        tagline: 'Dark red and charcoal, performance',
        primary: '#B71C1C',
        accent: '#263238',
        bg: '#FFFFFF',
        surface: '#F8F8F8',
        textPrimary: '#1A1A1A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🏎️ Fast & Powerful',
        gradFrom: '#B71C1C',
        gradTo: '#E53935',
        tag: 'Popular',
      },
      {
        id: 'auto-luxury',
        name: 'Luxury Auto',
        tagline: 'Gold on black, premium drive',
        primary: '#C8A951',
        accent: '#FFFFFF',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#C8A951',
        theme: 'dark',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'pill',
        mood: '🖤 Premium & Exclusive',
        gradFrom: '#0A0A0A',
        gradTo: '#C8A951',
        tag: 'Premium',
      },
      {
        id: 'auto-modern',
        name: 'Modern Garage',
        tagline: 'Clean blue and white, reliable',
        primary: '#0277BD',
        accent: '#FFFFFF',
        bg: '#F0F8FF',
        surface: '#FFFFFF',
        textPrimary: '#01395A',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '🔧 Reliable & Modern',
        gradFrom: '#0277BD',
        gradTo: '#29B6F6',
      },
      {
        id: 'auto-electric',
        name: 'Electric Future',
        tagline: 'Neon green on dark, EV vibes',
        primary: '#00E676',
        accent: '#1DE9B6',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#00E676',
        theme: 'dark',
        font: 'tech',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '⚡ Electric & Futuristic',
        gradFrom: '#00C853',
        gradTo: '#00E676',
        tag: 'Trending',
      },
    ],
  },

  Events: {
    emoji: '🎉',
    label: 'Events',
    description: 'Events & Celebrations',
    bgColor: '#FDF4FF',
    gradFrom: '#A855F7',
    gradTo: '#EC4899',
    presets: [
      {
        id: 'events-party',
        name: 'Party Vibes',
        tagline: 'Pink and purple, celebration mood',
        primary: '#E91E63',
        accent: '#9C27B0',
        bg: '#FFF5F9',
        surface: '#FFFFFF',
        textPrimary: '#5A0028',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '🎊 Fun & Festive',
        gradFrom: '#E91E63',
        gradTo: '#9C27B0',
        tag: 'Popular',
      },
      {
        id: 'events-corporate',
        name: 'Corporate Events',
        tagline: 'Navy and gold, professional',
        primary: '#1A237E',
        accent: '#C8A951',
        bg: '#FAFAF5',
        surface: '#FFFFFF',
        textPrimary: '#0D1A5E',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'elegant',
        layout: 'minimal',
        buttonStyle: 'square',
        mood: '🎖️ Professional & Smart',
        gradFrom: '#1A237E',
        gradTo: '#C8A951',
      },
      {
        id: 'events-creative',
        name: 'Creative Fest',
        tagline: 'Orange and teal, artsy energy',
        primary: '#E65100',
        accent: '#00ACC1',
        bg: '#FFFFF0',
        surface: '#FFFFFF',
        textPrimary: '#3E1500',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '🎭 Creative & Energetic',
        gradFrom: '#E65100',
        gradTo: '#00ACC1',
        tag: 'Trending',
      },
      {
        id: 'events-gala',
        name: 'Elegant Gala',
        tagline: 'Dark rose and gold, glamorous',
        primary: '#C8A951',
        accent: '#FFD700',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#C8A951',
        theme: 'dark',
        font: 'elegant',
        layout: 'magazine',
        buttonStyle: 'pill',
        mood: '✨ Glamorous & Grand',
        gradFrom: '#880E4F',
        gradTo: '#C8A951',
        tag: 'Premium',
      },
    ],
  },

  Technology: {
    emoji: '💻',
    label: 'Technology',
    description: 'Tech & Software',
    bgColor: '#EFF6FF',
    gradFrom: '#2563EB',
    gradTo: '#7C3AED',
    presets: [
      {
        id: 'tech-dark',
        name: 'Dark Mode Tech',
        tagline: 'Teal and cyan on pure black',
        primary: '#00BFA5',
        accent: '#00E5FF',
        bg: '#0A0A0A',
        surface: '#1A1A1A',
        textPrimary: '#FFFFFF',
        textSecondary: '#8B949E',
        theme: 'dark',
        font: 'tech',
        layout: 'hero',
        buttonStyle: 'square',
        mood: '🖥️ Dark & Powerful',
        gradFrom: '#006064',
        gradTo: '#00E5FF',
        tag: 'Popular',
      },
      {
        id: 'tech-clean',
        name: 'Clean SaaS',
        tagline: 'Deep blue, clean, trustworthy',
        primary: '#1565C0',
        accent: '#0288D1',
        bg: '#F5F8FF',
        surface: '#FFFFFF',
        textPrimary: '#0D2060',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '☁️ Clean & Scalable',
        gradFrom: '#1565C0',
        gradTo: '#0288D1',
      },
      {
        id: 'tech-gradient',
        name: 'Gradient Wave',
        tagline: 'Purple to pink, vibrant SaaS',
        primary: '#7B1FA2',
        accent: '#E91E63',
        bg: '#FAF5FF',
        surface: '#FFFFFF',
        textPrimary: '#3A0063',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '🌈 Vibrant & Modern',
        gradFrom: '#7B1FA2',
        gradTo: '#E91E63',
        tag: 'Trending',
      },
      {
        id: 'tech-matrix',
        name: 'Matrix Green',
        tagline: 'Bright green on pure black, hacker',
        primary: '#00E676',
        accent: '#00BFA5',
        bg: '#0A0A0A',
        surface: '#111111',
        textPrimary: '#00E676',
        textSecondary: '#4CAF50',
        theme: 'dark',
        font: 'tech',
        layout: 'list',
        buttonStyle: 'square',
        mood: '🟩 Matrix & Code',
        gradFrom: '#0A0A0A',
        gradTo: '#00E676',
      },
    ],
  },

  'Non-Profit': {
    emoji: '🤝',
    label: 'Non-Profit',
    description: 'NGO & Community',
    bgColor: '#F0FDF4',
    gradFrom: '#16A34A',
    gradTo: '#4ADE80',
    presets: [
      {
        id: 'npo-green',
        name: 'Green Earth',
        tagline: 'Forest green and orange, cause-driven',
        primary: '#2E7D32',
        accent: '#FF8C00',
        bg: '#F5FFF5',
        surface: '#FFFFFF',
        textPrimary: '#1B3D1C',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '🌍 Environmental & Caring',
        gradFrom: '#2E7D32',
        gradTo: '#FF8C00',
        tag: 'Popular',
      },
      {
        id: 'npo-hope',
        name: 'Hope Sky',
        tagline: 'Sky blue and sunny yellow',
        primary: '#1565C0',
        accent: '#FFC107',
        bg: '#F0F4FF',
        surface: '#FFFFFF',
        textPrimary: '#0D2060',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '💙 Hopeful & Uplifting',
        gradFrom: '#1565C0',
        gradTo: '#FFC107',
      },
      {
        id: 'npo-community',
        name: 'Community Spirit',
        tagline: 'Deep red and white, passionate',
        primary: '#C62828',
        accent: '#FFCDD2',
        bg: '#FFF5F5',
        surface: '#FFFFFF',
        textPrimary: '#5A0000',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '❤️ Passionate & United',
        gradFrom: '#C62828',
        gradTo: '#EF9A9A',
      },
      {
        id: 'npo-earth',
        name: 'Earth Roots',
        tagline: 'Brown and olive green, grounded',
        primary: '#5D4037',
        accent: '#558B2F',
        bg: '#FFF8F0',
        surface: '#FFFFFF',
        textPrimary: '#2E1503',
        textSecondary: '#78716C',
        theme: 'light',
        font: 'classic',
        layout: 'minimal',
        buttonStyle: 'rounded',
        mood: '🌱 Grounded & Authentic',
        gradFrom: '#5D4037',
        gradTo: '#558B2F',
      },
    ],
  },

  Other: {
    emoji: '🏢',
    label: 'Other',
    description: 'General Business',
    bgColor: '#F8FAFC',
    gradFrom: '#64748B',
    gradTo: '#94A3B8',
    presets: [
      {
        id: 'other-classic',
        name: 'Classic Blue',
        tagline: 'Reliable blue and gray',
        primary: '#1565C0',
        accent: '#78909C',
        bg: '#F5F8FF',
        surface: '#FFFFFF',
        textPrimary: '#0D2060',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'modern',
        layout: 'card',
        buttonStyle: 'rounded',
        mood: '🔵 Reliable & Clear',
        gradFrom: '#1565C0',
        gradTo: '#78909C',
        tag: 'Popular',
      },
      {
        id: 'other-purple',
        name: 'Modern Purple',
        tagline: 'Deep purple, forward-thinking',
        primary: '#7B1FA2',
        accent: '#CE93D8',
        bg: '#FAF5FF',
        surface: '#FFFFFF',
        textPrimary: '#3A0063',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'bold',
        layout: 'hero',
        buttonStyle: 'pill',
        mood: '💜 Modern & Bold',
        gradFrom: '#7B1FA2',
        gradTo: '#CE93D8',
      },
      {
        id: 'other-green',
        name: 'Fresh Green',
        tagline: 'Fresh green and dark, vibrant',
        primary: '#2E7D32',
        accent: '#1A1A2E',
        bg: '#F5FFF5',
        surface: '#FFFFFF',
        textPrimary: '#1B3D1C',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'playful',
        layout: 'grid',
        buttonStyle: 'rounded',
        mood: '🌿 Fresh & Energetic',
        gradFrom: '#2E7D32',
        gradTo: '#66BB6A',
      },
      {
        id: 'other-orange',
        name: 'Bold Orange',
        tagline: 'Vibrant orange with navy',
        primary: '#E65100',
        accent: '#1A237E',
        bg: '#FFFAF5',
        surface: '#FFFFFF',
        textPrimary: '#3E1500',
        textSecondary: '#6B7280',
        theme: 'light',
        font: 'classic',
        layout: 'minimal',
        buttonStyle: 'square',
        mood: '🟠 Vibrant & Assertive',
        gradFrom: '#E65100',
        gradTo: '#FF7043',
        tag: 'Trending',
      },
    ],
  },
};

export const categoryList = Object.entries(categoryData).map(([key, val]) => ({
  id: key,
  emoji: val.emoji,
  label: val.label,
  description: val.description,
  bgColor: val.bgColor,
  gradFrom: val.gradFrom,
  gradTo: val.gradTo,
}));

export function getPresetsForCategory(category: string): StylePreset[] {
  return (categoryData[category] ?? categoryData['Other']).presets;
}

export function getPresetById(category: string, presetId: string): StylePreset | undefined {
  const presets = getPresetsForCategory(category);
  return presets.find((p) => p.id === presetId) ?? presets[0];
}

export const fontStyleInfo: Record<string, { label: string; desc: string; sample: string }> = {
  modern: { label: 'Modern', desc: 'Clean sans-serif', sample: 'Aa' },
  classic: { label: 'Classic', desc: 'Balanced & trustworthy', sample: 'Aa' },
  bold: { label: 'Bold', desc: 'Heavy & impactful', sample: 'Aa' },
  elegant: { label: 'Elegant', desc: 'Refined serif', sample: 'Aa' },
  playful: { label: 'Playful', desc: 'Rounded & fun', sample: 'Aa' },
  tech: { label: 'Tech', desc: 'Mono & precise', sample: 'A_' },
};

export const layoutStyleInfo: Record<string, { label: string; desc: string; icon: string }> = {
  card: { label: 'Card View', desc: 'Organized cards', icon: '⊞' },
  hero: { label: 'Hero Banner', desc: 'Full-width impact', icon: '▬' },
  grid: { label: 'Grid Layout', desc: 'Visual grid', icon: '⊟' },
  minimal: { label: 'Minimal', desc: 'Clean whitespace', icon: '═' },
  magazine: { label: 'Magazine', desc: 'Editorial multi-col', icon: '≡' },
  list: { label: 'List View', desc: 'Clean vertical list', icon: '☰' },
};
