-- redeem_rocket_premium → Supabase PostgreSQL
-- Review and run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS "audit_logs" (
  "id" text NOT NULL,
  "user_id" text,
  "action" text NOT NULL,
  "resource_type" text,
  "resource_id" text,
  "details" jsonb,
  "ip_address" text,
  "user_agent" text,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "businesses" (
  "id" text NOT NULL,
  "merchant_id" text,
  "name" text NOT NULL,
  "category" text,
  "description" text,
  "address" text,
  "phone" text,
  "email" text,
  "rating" numeric,
  "review_count" integer,
  "is_verified" integer,
  "created_at" timestamptz NOT NULL,
  "is_active" integer,
  "featured" integer,
  "views_count" integer,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "coupon_redemptions" (
  "id" text NOT NULL,
  "coupon_id" text,
  "customer_id" text,
  "business_id" text,
  "redemption_code" text,
  "amount_saved" numeric,
  "redeemed_at" timestamptz,
  "status" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "coupons" (
  "id" text NOT NULL,
  "merchant_id" text,
  "business_id" text,
  "title" text NOT NULL,
  "description" text,
  "discount_type" text,
  "discount_value" numeric,
  "minimum_amount" numeric,
  "maximum_discount" numeric,
  "total_quantity" integer,
  "used_quantity" integer,
  "valid_from" timestamptz,
  "valid_until" timestamptz,
  "terms_conditions" text,
  "coupon_code" text,
  "status" text,
  "target_subscription" jsonb,
  "created_by" text,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "customer_profiles" (
  "id" text NOT NULL,
  "user_id" text,
  "subscription_plan" text,
  "wallet_balance" numeric,
  "loyalty_points" integer,
  "streak_days" integer,
  "referral_code" text,
  "referred_by" text,
  "location_lat" numeric,
  "location_lng" numeric,
  "preferences" jsonb,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "financial_reports" (
  "id" text NOT NULL,
  "report_date" date NOT NULL,
  "report_type" text,
  "gross_revenue" numeric,
  "net_revenue" numeric,
  "refunds" numeric,
  "chargebacks" numeric,
  "platform_fees" numeric,
  "payment_gateway_fees" numeric,
  "commission_earned" numeric,
  "supplier_payouts" numeric,
  "marketing_spend" numeric,
  "operational_costs" numeric,
  "customer_support_costs" numeric,
  "technology_costs" numeric,
  "administrative_costs" numeric,
  "gross_profit" numeric,
  "net_profit" numeric,
  "tax_liability" numeric,
  "cash_flow" numeric,
  "accounts_receivable" numeric,
  "accounts_payable" numeric,
  "inventory_value" numeric,
  "working_capital" numeric,
  "customer_acquisition_cost" numeric,
  "customer_lifetime_value" numeric,
  "return_on_investment" numeric,
  "profit_margin" numeric,
  "growth_rate" numeric,
  "burn_rate" numeric,
  "runway_months" integer,
  "category_breakdown" jsonb,
  "supplier_breakdown" jsonb,
  "payment_method_breakdown" jsonb,
  "geographic_breakdown" jsonb,
  "currency_breakdown" jsonb,
  "created_at" timestamptz,
  "generated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "hot_searches" (
  "id" text NOT NULL,
  "search_term" text NOT NULL,
  "normalized_term" text NOT NULL,
  "category_id" text,
  "product_id" text,
  "user_id" text,
  "session_id" text,
  "search_type" text,
  "search_context" jsonb,
  "search_filters" jsonb,
  "search_count" integer,
  "result_count" integer,
  "clicked_results" integer,
  "converted_searches" integer,
  "revenue_generated" numeric,
  "is_trending" integer,
  "trending_score" numeric,
  "priority_score" numeric,
  "sentiment_score" numeric,
  "related_terms" jsonb,
  "suggested_improvements" jsonb,
  "last_searched" timestamptz,
  "first_searched" timestamptz,
  "peak_search_date" date,
  "geographic_data" jsonb,
  "device_data" jsonb,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "invoices" (
  "id" text NOT NULL,
  "order_id" text,
  "customer_id" text NOT NULL,
  "supplier_id" text,
  "invoice_number" text NOT NULL,
  "invoice_type" text,
  "invoice_date" date NOT NULL,
  "due_date" date,
  "billing_address" jsonb,
  "shipping_address" jsonb,
  "line_items" jsonb NOT NULL,
  "subtotal" numeric NOT NULL,
  "discount_amount" numeric,
  "tax_breakdown" jsonb,
  "total_tax" numeric,
  "total_amount" numeric NOT NULL,
  "currency" text,
  "payment_terms" text,
  "notes" text,
  "status" text,
  "payment_status" text,
  "paid_amount" numeric,
  "balance_amount" numeric NOT NULL,
  "last_payment_date" timestamptz,
  "pdf_url" text,
  "sent_at" timestamptz,
  "viewed_at" timestamptz,
  "paid_at" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "loyalty_programs" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "program_type" text,
  "points_balance" integer,
  "points_earned_lifetime" integer,
  "points_redeemed_lifetime" integer,
  "current_tier" text,
  "tier_progress" jsonb,
  "tier_benefits" jsonb,
  "cashback_balance" numeric,
  "cashback_earned_lifetime" numeric,
  "cashback_redeemed_lifetime" numeric,
  "membership_start_date" date,
  "membership_expiry_date" date,
  "status" text,
  "achievements" jsonb,
  "special_privileges" jsonb,
  "birthday_month" integer,
  "anniversary_date" date,
  "preferences" jsonb,
  "communication_opt_in" integer,
  "last_activity_date" date,
  "last_tier_update" date,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "marketing_campaigns" (
  "id" text NOT NULL,
  "campaign_name" text NOT NULL,
  "campaign_code" text NOT NULL,
  "campaign_type" text,
  "campaign_objective" text,
  "target_audience" jsonb,
  "budget" numeric,
  "spend" numeric,
  "start_date" date NOT NULL,
  "end_date" date,
  "status" text,
  "content_details" jsonb,
  "channels" jsonb,
  "utm_parameters" jsonb,
  "success_metrics" jsonb,
  "target_impressions" integer,
  "target_clicks" integer,
  "target_conversions" integer,
  "actual_impressions" integer,
  "actual_clicks" integer,
  "actual_conversions" integer,
  "click_through_rate" numeric,
  "conversion_rate" numeric,
  "cost_per_click" numeric,
  "cost_per_conversion" numeric,
  "return_on_ad_spend" numeric,
  "revenue_generated" numeric,
  "leads_generated" integer,
  "customers_acquired" integer,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "merchant_profiles" (
  "id" text NOT NULL,
  "user_id" text,
  "business_name" text NOT NULL,
  "business_category" text,
  "gstin" text,
  "business_address" text,
  "location_lat" numeric,
  "location_lng" numeric,
  "verification_status" text,
  "verification_documents" jsonb,
  "business_hours" jsonb,
  "contact_person" text,
  "website_url" text,
  "social_media" jsonb,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "type" text NOT NULL,
  "message" text NOT NULL,
  "is_read" integer,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "order_status_history" (
  "id" text NOT NULL,
  "order_id" text NOT NULL,
  "previous_status" text,
  "new_status" text NOT NULL,
  "status_type" text,
  "changed_by" text,
  "change_reason" text,
  "change_notes" text,
  "automated" integer,
  "metadata" jsonb,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "orders" (
  "id" text NOT NULL,
  "customer_id" text NOT NULL,
  "business_id" text NOT NULL,
  "status" text,
  "total_amount" numeric NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "otp_verifications" (
  "id" text NOT NULL,
  "phone" text,
  "email" text,
  "otp_code" text,
  "firebase_session_id" text,
  "purpose" text,
  "expires_at" timestamptz,
  "is_verified" integer,
  "attempts" integer,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "payments" (
  "id" text NOT NULL,
  "order_id" text,
  "user_id" text NOT NULL,
  "payment_reference" text NOT NULL,
  "payment_type" text,
  "amount" numeric NOT NULL,
  "currency" text,
  "payment_method" text,
  "payment_gateway" text,
  "gateway_transaction_id" text,
  "gateway_response" jsonb,
  "card_details" jsonb,
  "upi_details" jsonb,
  "bank_details" jsonb,
  "emi_details" jsonb,
  "status" text,
  "failure_reason" text,
  "gateway_fee" numeric,
  "platform_fee" numeric,
  "tax_amount" numeric,
  "net_amount" numeric NOT NULL,
  "initiated_at" timestamptz,
  "authorized_at" timestamptz,
  "captured_at" timestamptz,
  "failed_at" timestamptz,
  "refunded_at" timestamptz,
  "refund_reference" text,
  "refund_amount" numeric,
  "dispute_id" text,
  "dispute_status" text,
  "reconciliation_status" text,
  "reconciliation_date" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "platform_analytics" (
  "id" text NOT NULL,
  "date_recorded" date NOT NULL,
  "period_type" text,
  "total_users" integer,
  "active_users" integer,
  "new_users" integer,
  "returning_users" integer,
  "customer_users" integer,
  "supplier_users" integer,
  "merchant_users" integer,
  "total_products" integer,
  "active_products" integer,
  "new_products" integer,
  "total_suppliers" integer,
  "active_suppliers" integer,
  "verified_suppliers" integer,
  "total_orders" integer,
  "completed_orders" integer,
  "cancelled_orders" integer,
  "returned_orders" integer,
  "total_order_value" numeric,
  "average_order_value" numeric,
  "total_revenue" numeric,
  "total_commission" numeric,
  "total_margin" numeric,
  "gross_profit" numeric,
  "net_profit" numeric,
  "customer_acquisition_cost" numeric,
  "customer_lifetime_value" numeric,
  "conversion_rate" numeric,
  "cart_abandonment_rate" numeric,
  "repeat_purchase_rate" numeric,
  "supplier_performance_avg" numeric,
  "customer_satisfaction_score" numeric,
  "website_visits" integer,
  "unique_visitors" integer,
  "page_views" integer,
  "bounce_rate" numeric,
  "session_duration_avg" integer,
  "mobile_traffic_percentage" numeric,
  "top_categories" jsonb,
  "top_products" jsonb,
  "top_suppliers" jsonb,
  "top_search_terms" jsonb,
  "geographic_distribution" jsonb,
  "traffic_sources" jsonb,
  "marketing_attribution" jsonb,
  "seasonal_trends" jsonb,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "premium_categories" (
  "id" text NOT NULL,
  "parent_id" text,
  "category_key" text NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "description" text,
  "detailed_description" text,
  "icon_url" text,
  "banner_image_url" text,
  "display_order" integer,
  "is_active" integer,
  "is_featured" integer,
  "seo_title" text,
  "seo_description" text,
  "seo_keywords" text,
  "meta_tags" jsonb,
  "commission_rate" numeric,
  "minimum_margin" numeric,
  "category_attributes" jsonb,
  "filters_config" jsonb,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "premium_orders" (
  "id" text NOT NULL,
  "order_number" text NOT NULL,
  "customer_id" text NOT NULL,
  "supplier_id" text NOT NULL,
  "order_type" text,
  "order_source" text,
  "customer_details" jsonb,
  "billing_address" jsonb,
  "shipping_address" jsonb,
  "subtotal" numeric NOT NULL,
  "tax_amount" numeric,
  "shipping_cost" numeric,
  "discount_amount" numeric,
  "total_amount" numeric NOT NULL,
  "currency" text,
  "platform_commission" numeric,
  "supplier_payout" numeric,
  "margin_amount" numeric,
  "order_status" text,
  "payment_status" text,
  "fulfillment_status" text,
  "payment_method" text,
  "payment_reference" text,
  "special_instructions" text,
  "internal_notes" text,
  "priority" text,
  "estimated_delivery_date" date,
  "actual_delivery_date" date,
  "delivery_window" jsonb,
  "tracking_number" text,
  "courier_partner" text,
  "customer_rating" integer,
  "customer_feedback" text,
  "supplier_rating" integer,
  "supplier_feedback" text,
  "is_gift" integer,
  "gift_message" text,
  "referral_code" text,
  "coupon_code" text,
  "utm_source" text,
  "utm_medium" text,
  "utm_campaign" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "completed_at" timestamptz,
  "cancelled_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "premium_products" (
  "id" text NOT NULL,
  "category_id" text NOT NULL,
  "product_code" text NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "short_description" text,
  "detailed_description" text,
  "price_range_min" numeric,
  "price_range_max" numeric,
  "base_price" numeric,
  "market_price" numeric,
  "estimated_margin" numeric,
  "minimum_margin" numeric,
  "weight_kg" numeric,
  "dimensions" jsonb,
  "monthly_search_volume" integer,
  "product_tags" text,
  "product_attributes" jsonb,
  "technical_specifications" jsonb,
  "features" jsonb,
  "benefits" jsonb,
  "use_cases" jsonb,
  "target_audience" jsonb,
  "brand" text,
  "model_number" text,
  "warranty_info" jsonb,
  "certifications" jsonb,
  "compliance_info" jsonb,
  "is_seasonal" integer,
  "seasonality_data" jsonb,
  "complexity_level" text,
  "installation_required" integer,
  "assembly_required" integer,
  "status" text,
  "visibility" text,
  "is_featured" integer,
  "is_trending" integer,
  "views_count" integer,
  "inquiries_count" integer,
  "orders_count" integer,
  "rating" numeric,
  "rating_count" integer,
  "review_count" integer,
  "seo_title" text,
  "seo_description" text,
  "seo_keywords" text,
  "meta_tags" jsonb,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "promotions" (
  "id" text NOT NULL,
  "promotion_name" text NOT NULL,
  "promotion_code" text NOT NULL,
  "promotion_type" text,
  "discount_type" text,
  "discount_value" numeric NOT NULL,
  "maximum_discount" numeric,
  "minimum_order_value" numeric,
  "applicable_products" jsonb,
  "applicable_categories" jsonb,
  "applicable_suppliers" jsonb,
  "target_customers" jsonb,
  "usage_limit_total" integer,
  "usage_limit_per_customer" integer,
  "used_count" integer,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" text,
  "auto_apply" integer,
  "stackable" integer,
  "terms_and_conditions" text,
  "promotion_banner_url" text,
  "email_template_id" text,
  "sms_template" text,
  "success_metrics" jsonb,
  "budget" numeric,
  "cost_incurred" numeric,
  "revenue_generated" numeric,
  "orders_influenced" integer,
  "new_customers_acquired" integer,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "referrals" (
  "id" text NOT NULL,
  "referrer_id" text NOT NULL,
  "referee_id" text,
  "referral_code" text NOT NULL,
  "referral_type" text,
  "referral_source" text,
  "referee_email" text,
  "referee_phone" text,
  "status" text,
  "qualification_criteria" jsonb,
  "qualified_at" timestamptz,
  "referrer_reward_type" text,
  "referrer_reward_value" numeric,
  "referrer_reward_status" text,
  "referee_reward_type" text,
  "referee_reward_value" numeric,
  "referee_reward_status" text,
  "first_order_id" text,
  "first_order_value" numeric,
  "total_orders_by_referee" integer,
  "total_value_by_referee" numeric,
  "commission_rate" numeric,
  "total_commission_earned" numeric,
  "expires_at" timestamptz,
  "notes" text,
  "tracking_data" jsonb,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
  "id" text NOT NULL,
  "user_id" text,
  "token_hash" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "is_revoked" integer,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reviews" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "business_id" text NOT NULL,
  "rating" integer NOT NULL,
  "comment" text,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "rewards" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "points" integer NOT NULL,
  "type" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "shipping_details" (
  "id" text NOT NULL,
  "order_id" text NOT NULL,
  "shipping_method" text,
  "courier_partner" text,
  "tracking_number" text,
  "shipping_label_url" text,
  "pickup_address" jsonb,
  "delivery_address" jsonb NOT NULL,
  "package_details" jsonb,
  "weight_kg" numeric,
  "dimensions" jsonb,
  "shipping_cost" numeric NOT NULL,
  "insurance_cost" numeric,
  "cod_charges" numeric,
  "total_shipping_cost" numeric NOT NULL,
  "estimated_delivery_date" date,
  "actual_pickup_date" date,
  "actual_delivery_date" date,
  "delivery_attempts" integer,
  "delivery_instructions" text,
  "special_handling" jsonb,
  "status" text,
  "tracking_events" jsonb,
  "delivery_confirmation" jsonb,
  "delivery_proof_url" text,
  "recipient_name" text,
  "recipient_phone" text,
  "delivery_notes" text,
  "exception_details" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "staff_profiles" (
  "id" text NOT NULL,
  "user_id" text,
  "employee_id" text,
  "department" text,
  "territory" text,
  "manager_level" text,
  "permissions" jsonb,
  "performance_metrics" jsonb,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "supplier_contracts" (
  "id" text NOT NULL,
  "supplier_id" text NOT NULL,
  "contract_number" text NOT NULL,
  "contract_type" text,
  "title" text NOT NULL,
  "description" text,
  "contract_value" numeric,
  "currency" text,
  "start_date" date NOT NULL,
  "end_date" date,
  "renewal_terms" jsonb,
  "payment_terms" jsonb,
  "delivery_terms" jsonb,
  "quality_requirements" jsonb,
  "performance_metrics" jsonb,
  "penalties" jsonb,
  "bonuses" jsonb,
  "termination_clauses" jsonb,
  "dispute_resolution" text,
  "governing_law" text,
  "contract_documents" jsonb,
  "status" text,
  "signed_by_supplier" text,
  "signed_by_company" text,
  "supplier_signature_date" timestamptz,
  "company_signature_date" timestamptz,
  "next_review_date" date,
  "performance_rating" numeric,
  "compliance_status" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "supplier_payments" (
  "id" text NOT NULL,
  "supplier_id" text NOT NULL,
  "order_id" text,
  "invoice_number" text,
  "payment_reference" text,
  "payment_type" text,
  "amount" numeric NOT NULL,
  "currency" text,
  "tax_amount" numeric,
  "fees" numeric,
  "net_amount" numeric NOT NULL,
  "payment_method" text,
  "payment_gateway" text,
  "transaction_id" text,
  "gateway_response" jsonb,
  "payment_date" timestamptz,
  "due_date" date,
  "status" text,
  "failure_reason" text,
  "reconciliation_status" text,
  "reconciliation_date" timestamptz,
  "notes" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "supplier_performance" (
  "id" text NOT NULL,
  "supplier_id" text NOT NULL,
  "evaluation_period_start" date NOT NULL,
  "evaluation_period_end" date NOT NULL,
  "total_orders" integer,
  "completed_orders" integer,
  "cancelled_orders" integer,
  "returned_orders" integer,
  "total_value" numeric,
  "average_order_value" numeric,
  "on_time_deliveries" integer,
  "late_deliveries" integer,
  "early_deliveries" integer,
  "average_delivery_time" numeric,
  "quality_issues" integer,
  "customer_complaints" integer,
  "positive_reviews" integer,
  "negative_reviews" integer,
  "response_time_hours" numeric,
  "communication_rating" numeric,
  "product_quality_rating" numeric,
  "service_quality_rating" numeric,
  "price_competitiveness" numeric,
  "innovation_score" numeric,
  "sustainability_score" numeric,
  "compliance_violations" integer,
  "contract_adherence" numeric,
  "overall_performance_score" numeric,
  "performance_grade" text,
  "improvement_areas" jsonb,
  "strengths" jsonb,
  "action_items" jsonb,
  "evaluator_id" text,
  "evaluation_date" timestamptz,
  "next_evaluation_due" date,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "supplier_products" (
  "id" text NOT NULL,
  "product_id" text NOT NULL,
  "supplier_id" text NOT NULL,
  "supplier_product_code" text,
  "supplier_product_name" text,
  "supplier_price" numeric,
  "bulk_pricing" jsonb,
  "supplier_margin" numeric,
  "cost_breakdown" jsonb,
  "lead_time_days" integer,
  "minimum_quantity" integer,
  "maximum_quantity" integer,
  "stock_quantity" integer,
  "stock_status" text,
  "availability_schedule" jsonb,
  "product_condition" text,
  "quality_grade" text,
  "warranty_offered" text,
  "installation_service" integer,
  "maintenance_service" integer,
  "customization_available" integer,
  "customization_options" jsonb,
  "shipping_info" jsonb,
  "special_instructions" text,
  "is_exclusive" integer,
  "is_preferred" integer,
  "priority_level" integer,
  "status" text,
  "performance_metrics" jsonb,
  "last_price_update" timestamptz,
  "last_stock_update" timestamptz,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "suppliers" (
  "id" text NOT NULL,
  "supplier_code" text NOT NULL,
  "name" text NOT NULL,
  "legal_name" text,
  "brand_name" text,
  "category" text NOT NULL,
  "speciality" text,
  "business_type" text,
  "company_size" text,
  "establishment_year" text,
  "location" text,
  "full_address" jsonb,
  "contact_info" jsonb,
  "business_hours" jsonb,
  "services" jsonb,
  "capabilities" jsonb,
  "certifications" jsonb,
  "licenses" jsonb,
  "insurance_info" jsonb,
  "bank_details" jsonb,
  "tax_info" jsonb,
  "margin_potential" text,
  "minimum_order_value" numeric,
  "maximum_order_value" numeric,
  "delivery_time_days" text,
  "supported_categories" jsonb,
  "supported_locations" jsonb,
  "payment_terms" jsonb,
  "return_policy" text,
  "warranty_policy" text,
  "quality_standards" jsonb,
  "sustainability_practices" jsonb,
  "rating" numeric,
  "total_orders" integer,
  "total_revenue" numeric,
  "total_products" integer,
  "response_time_hours" integer,
  "fulfillment_rate" numeric,
  "quality_score" numeric,
  "delivery_performance" numeric,
  "communication_score" numeric,
  "verification_status" text,
  "verification_level" text,
  "verification_date" timestamptz,
  "verification_documents" jsonb,
  "is_active" integer,
  "is_featured" integer,
  "is_preferred" integer,
  "performance_score" numeric,
  "risk_score" numeric,
  "compliance_status" text,
  "last_audit_date" timestamptz,
  "next_audit_due" timestamptz,
  "onboarding_status" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "system_configurations" (
  "id" text NOT NULL,
  "config_key" text NOT NULL,
  "config_value" text,
  "config_type" text,
  "category" text NOT NULL,
  "description" text,
  "is_encrypted" integer,
  "is_public" integer,
  "is_editable" integer,
  "validation_rules" jsonb,
  "default_value" text,
  "environment" text,
  "requires_restart" integer,
  "last_modified_by" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "transactions" (
  "id" text NOT NULL,
  "user_id" text,
  "type" text,
  "amount" numeric NOT NULL,
  "description" text,
  "reference_type" text,
  "reference_id" text,
  "balance_after" numeric,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_activity_logs" (
  "id" text NOT NULL,
  "user_id" text,
  "session_id" text,
  "activity_type" text NOT NULL,
  "activity_description" text,
  "resource_type" text,
  "resource_id" text,
  "old_values" jsonb,
  "new_values" jsonb,
  "ip_address" text,
  "user_agent" text,
  "request_method" text,
  "request_url" text,
  "response_status" integer,
  "processing_time_ms" integer,
  "metadata" jsonb,
  "severity" text,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_permissions" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "permission_type" text,
  "permission_name" text NOT NULL,
  "permission_value" text,
  "resource_type" text,
  "resource_id" text,
  "granted_by" text,
  "granted_at" timestamptz,
  "expires_at" timestamptz,
  "is_active" integer,
  "conditions" jsonb,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_profiles" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "first_name" text,
  "last_name" text,
  "date_of_birth" date,
  "gender" text,
  "nationality" text,
  "preferred_language" text,
  "timezone" text,
  "business_name" text,
  "business_type" text,
  "business_registration" text,
  "gst_number" text,
  "pan_number" text,
  "aadhar_number" text,
  "business_address" jsonb,
  "billing_address" jsonb,
  "shipping_address" jsonb,
  "emergency_contact" jsonb,
  "bank_details" jsonb,
  "preferred_categories" jsonb,
  "budget_range" jsonb,
  "communication_preferences" jsonb,
  "social_media_links" jsonb,
  "kyc_status" text,
  "kyc_documents" jsonb,
  "credit_limit" numeric,
  "credit_used" numeric,
  "total_orders" integer,
  "total_spent" numeric,
  "total_saved" numeric,
  "average_order_value" numeric,
  "lifetime_value" numeric,
  "acquisition_channel" text,
  "referral_code" text,
  "referred_by" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" text NOT NULL,
  "user_id" text NOT NULL,
  "session_token" text NOT NULL,
  "refresh_token" text,
  "token_hash" text NOT NULL,
  "device_info" jsonb,
  "browser_info" jsonb,
  "ip_address" text,
  "location_info" jsonb,
  "is_mobile" integer,
  "session_type" text,
  "expires_at" timestamptz NOT NULL,
  "last_activity" timestamptz,
  "is_active" integer,
  "logout_reason" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_signals" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text,
  "product_id" text,
  "signal_type" text,
  "created_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "name" text NOT NULL,
  "role" text,
  "is_active" integer,
  "last_login" timestamptz,
  "last_login_ip" text,
  "login_count" integer,
  "failed_login_attempts" integer,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "password_hash" text,
  "firebase_uid" text,
  "username" text,
  "status" text NOT NULL,
  "profile_image_url" text,
  "bio" text,
  "date_of_birth" date,
  "gender" text,
  "is_verified" integer,
  "email_verified" integer,
  "email_verified_at" timestamptz,
  "phone_verified" integer,
  "phone_verified_at" timestamptz,
  "two_factor_enabled" integer,
  "two_factor_secret" text,
  "last_failed_login" timestamptz,
  "account_locked_until" timestamptz,
  "password_reset_token" text,
  "password_reset_expires" timestamptz,
  "email_verification_token" text,
  "email_verification_expires" timestamptz,
  "phone_verification_token" text,
  "phone_verification_expires" timestamptz,
  "terms_accepted" integer,
  "terms_accepted_at" timestamptz,
  "privacy_policy_accepted" integer,
  "privacy_policy_accepted_at" timestamptz,
  "marketing_emails_allowed" integer,
  "push_notifications_enabled" integer,
  "sms_notifications_enabled" integer,
  "timezone" text,
  "language" text,
  "currency" text,
  "social_media" jsonb,
  "reward_points" integer,
  "total_points_earned" integer,
  "loyalty_tier" text,
  "created_by" text,
  "updated_by" text,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
);
